name: Build (reusable)

on:
  workflow_call:
    inputs:
      publish_tag:
        required: false
        type: string
        default: none
      bump:
        required: false
        type: string
        default: patch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "publish_tag=${{ inputs.publish_tag }} bump=${{ inputs.bump }}"
