name: Build (reusable)

on:
  workflow_call:
    inputs:
      publish_tag:
        required: false
        type: string
        default: none
      bump:
        required: false
        type: string
        default: patch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tracht-digital-solutions'

      - run: echo "node configured"
